### ISSUE TITLE
[2pt] Error on Fetch Shipping Rates

### ISSUE THREAD

**Issue by dottenbr** [elexess/erp-shipment#118]
https://erp.eso-electronic.com/desk#Form/Shipment/SHIPMENT-01417

Why can I book this and then when I fetch the shipping rates it throws the error? It would be better if the constraints would be caught before I fetch the shipping rates so I don't have to cancel this.

![image](https://user-images.githubusercontent.com/9136094/129183050-98d93d81-71d3-497d-8117-98550fd2c1a9.png)

**Comment by dottenbr** [comment]
Had to cancel again because it was still not right https://erp.eso-electronic.com/desk#Form/Shipment/SHIPMENT-01417-1

**Comment by dottenbr** [comment]
Finally it worked after I modified all of this

![image](https://user-images.githubusercontent.com/9136094/129184025-3039800f-e8e8-45d8-8fdc-03727ad76cbb.png)

**Comment by francitj** [comment]
STAGING TEST PASSED

With a proper error message
![chrome-capture (29)](https://user-images.githubusercontent.com/74176335/129838289-8509c72e-1343-404f-8390-6a77fbe98cf3.gif)


Submitted under the correct condition
![chrome-capture (30)](https://user-images.githubusercontent.com/74176335/129839083-2f39c96c-4aca-4910-9ae7-2b6bb2a36e28.gif)

**Comment by jeremythegreat01** [comment]
Related Issue and Released to the User in https://github.com/elexess/erp-shipment/issues/123#issuecomment-908876277
