### ISSUE TITLE
Unable to submit SHIPMENT-01456

### ISSUE THREAD

**Issue by dottenbr** [elexess/erp-shipment#123]
https://erp.eso-electronic.com/desk#Form/Shipment/SHIPMENT-01456

The error message is unclear to me, is the customer's street address too long? I count 21 characters in "Otto-Schott-Strasse 2".

![image](https://user-images.githubusercontent.com/9136094/131321391-82437837-09d9-4b04-9d54-2bd6c92e422c.png)

**Comment by dottenbr** [comment]
It seems that in order to fix this my colleagues desperately created a couple of more shipments:

- Original shipment: https://erp.eso-electronic.com/desk#Form/Shipment/SHIPMENT-01456
- Duplicate: https://erp.eso-electronic.com/desk#Form/Shipment/SHIPMENT-01457
- Duplicate: https://erp.eso-electronic.com/desk#Form/Shipment/SHIPMENT-01458

**Comment by dottenbr** [comment]
I suspect this is related to the latest server update and caused by this https://github.com/elexess/erp-shipment/commit/5aa5f943183fd8d504f48913e7aec8a15f8579f8

**Comment by kkulloters** [comment]
I found out that there's an old validation during submit I will  just remove this
![old validation](https://user-images.githubusercontent.com/40702858/131325423-5d069856-7129-499c-8aeb-fdcf0217d587.jpg)

**Comment by dottenbr** [comment]
I think in theory it's good to validate. But why does this trigger an error? The address of the pickup or delivery is not longer than 30 characters. Please also make the error message explicit to point the user to the right problem.

**Comment by dottenbr** [comment]
Sorry, I just noticed it's your day off. You can resolve it tomorrow morning that will be OK. We dealt with this individual case now by sending it with our delivery service. Please cancel all 3 documents tomorrow.

**Comment by kkulloters** [comment]
No worries @dottenbr  will continue tomorrow 

I tried printing the one that's being validated the pickup address is causing it just so weird cos it didn't show up during testing last week 
![image](https://user-images.githubusercontent.com/40702858/131328539-7d0811c8-ec28-4135-80fb-8a4f7ae62d97.png)

But I think it's just fine to remove cos there's also an old code that handle's more than  30 character
![old handler](https://user-images.githubusercontent.com/40702858/131329046-b9cc6ea8-f140-4a9b-ab49-9340a57d1625.jpg)

**Comment by kkulloters** [comment]
I will just remove the validation that Isaiah [added](https://github.com/elexess/erp-shipment/commit/05f61716b458ee749d534aabead046304e1caf48#diff-952589b3be937f368bc2d53ce388f59e72a8f8047556cba26553932f169bb366) since the address_title is not the one that is being put in the "street" payload for the letmeship API its the address_line1. And on my last PR I already handle it in let_me_ship.py when it is more than 35 characters it will split it into two and put the first 35 characters to "street" and the second half to "addressInfo1" and move the address_line2 to "addressInfo2"
![image](https://user-images.githubusercontent.com/40702858/131427454-b1cdfb23-f2a3-46e8-9db9-88925b209496.png)

**Comment by jeremythegreat01** [comment]
Comment from https://github.com/elexess/erp-shipment/issues/123#issuecomment-908206533
> It seems that in order to fix this my colleagues desperately created a couple of more shipments:
> 
> * Original shipment: https://erp.eso-electronic.com/desk#Form/Shipment/SHIPMENT-01456
> * Duplicate: https://erp.eso-electronic.com/desk#Form/Shipment/SHIPMENT-01457
> * Duplicate: https://erp.eso-electronic.com/desk#Form/Shipment/SHIPMENT-01458

Comment from https://github.com/elexess/erp-shipment/issues/123#issuecomment-908235142
> Sorry, I just noticed it's your day off. You can resolve it tomorrow morning that will be OK. We dealt with this individual case now by sending it with our delivery service. Please cancel all 3 documents tomorrow.

### Update
I checked the entries in production and they seem to have already been deleted.
![image](https://user-images.githubusercontent.com/35899441/131436850-d960f866-3197-4998-98af-141905b54c2f.png)
![image](https://user-images.githubusercontent.com/35899441/131436876-afbe71a1-5813-46c2-a7e1-21bdbe949467.png)
![image](https://user-images.githubusercontent.com/35899441/131436891-154133fa-cd2c-409f-b540-d0e3ccf34c5c.png)

**Comment by jeremythegreat01** [comment]
## STAGING TEST PASSED
### Scenario 1: Street is less than 30 characters = PASSED. No errors encountered.
https://staging.newmatik.com/desk#Form/Shipment/SHIPMENT-00028
![image](https://user-images.githubusercontent.com/35899441/131438288-f11cadda-da67-4ed9-8083-2d6f0e61468d.png)

### Scenario 2: Street is more than 30 characters = PASSED. Expected error is encountered.
https://staging.newmatik.com/desk#Form/Shipment/SHIPMENT-00029
![image](https://user-images.githubusercontent.com/35899441/131438195-16d5739e-075d-4b04-9ad8-3b841321da2b.png)

**Comment by kkulloters** [comment]
I also tested it on staging

Scenario 1: less than 35 characters
![Schott](https://user-images.githubusercontent.com/40702858/131438529-1ba50d7b-348f-4985-a810-c3997c65a8f7.gif)

Scenario 2: more than 35 characters
![lcsc](https://user-images.githubusercontent.com/40702858/131438564-9098b063-86ca-435d-9e63-6136c98be6da.gif)

**Comment by jeremythegreat01** [comment]
Update: Released by Vanessa to Dominik in the channel.

Release to User:
![image](https://user-images.githubusercontent.com/35899441/131439038-ef46b5db-d940-4239-9fde-f369911dacea.png)

Production Git Log:
![MicrosoftTeams-image](https://user-images.githubusercontent.com/35899441/131439096-fdc75567-8876-47ff-925f-7766fa357a37.png)
