### ISSUE TITLE
[2pt]Error occurred while fetching LetMeShip prices: ['Pickup order allowed only for domestic pickup.']

### ISSUE THREAD

**Issue by dottenbr** [elexess/erp-shipment#125]
![image](https://user-images.githubusercontent.com/9136094/134147129-d81e6df7-1440-406d-a6c0-c24c5a752f1c.png)

**Comment by kkulloters** [comment]
hello @jeremythegreat01 @creamdory 

what's the LMS region of romania?

I tried using the DE company with the same customer for the delivery address seems like it fetches the prices 
![image](https://user-images.githubusercontent.com/40702858/140042045-115f9901-82d8-43e0-b62c-e7a63a344d94.png)
![image](https://user-images.githubusercontent.com/40702858/140042112-bb3cbb25-bc98-456b-815e-7527065821ad.png)

So I tried to look in the letmeship [documentation](https://api.letmeship.com/#returns-a-listing-of-the-available-services-on-the-route-for-specified-shipment) seems like we need to change the  LMS region

**Comment by kkulloters** [comment]
hi @jeremythegreat01 

I tried putting LMS region and set to 'RO' it seems like it still show the same error 
![image](https://user-images.githubusercontent.com/40702858/140280442-03848f5f-8922-4c44-a2d1-5db7bcd1388e.png)

**Comment by jeremythegreat01** [comment]
Thanks for trying it out, @kkulloters. As of this writing, I have not received any responses from Dominik yet about the LMS-Regions in Europe.

**Comment by kkulloters** [comment]
Okay @jeremythegreat01 I'll just wait for the response thanks

**Comment by jeremythegreat01** [comment]
Hi @creamdory and @kkulloters, I tried messaging Dominik about this to confirm the LMS region of Romania, but I did not get a response.

Can we send out an email to LetMeShip instead?

**Comment by kkulloters** [comment]
hello Jeremy, that will be a good idea but if they don't have LMS region for Romania maybe changing the pickup type to 'Self delivery' when the company is 'SC ESO Electronic S.R.L' is maybe our other option with this

**Comment by kkulloters** [comment]
As discussed earlier during the poker planning will change the pickup type to "Self-delivery" when the company is 'SC ESO Electronic S.R.L' since letmeship api doesn't allow 'pickup' type when the company pickup address is in romania

cc: @creamdory

**Comment by francitj** [comment]
STAGING TEST PASSED:

Pickup type automatically changed to self-delivery upon saving.

before saving
![image](https://user-images.githubusercontent.com/74176335/142969808-74ad4d95-0d33-48a3-b526-f73d502653ae.png)

After saving
![image](https://user-images.githubusercontent.com/74176335/142969859-499b64ac-a729-448e-89af-156152b52e06.png)
