### ISSUE TITLE
Error when creating shipment 

### ISSUE THREAD

**Issue by kkulloters** [elexess/erp-shipment#127]
The error occurs when updating delivery note

![image](https://user-images.githubusercontent.com/40702858/135966895-68bbd213-e983-4ced-b062-9d0de748cf10.png)

**Comment by jeremythegreat01** [comment]
Since this is urgent as requested by Sonja and already tested locally by the developer. We will immediately move this to the Production server in the morning when there are no users in production.

**Comment by jeremythegreat01** [comment]
Note: Moved to production
![image](https://user-images.githubusercontent.com/35899441/136121982-5e1cb2c9-06b5-430b-9510-186ba49e4a78.png)

**Comment by jeremythegreat01** [comment]
Released to User via email (special case because Support Case was not working for her - but should be fixed now)
![image](https://user-images.githubusercontent.com/35899441/136122176-d24a6909-c45c-49a8-aeaa-4806d4f6ec00.png)
