### ISSUE TITLE
Can’t print shipping label 

### ISSUE THREAD

**Issue by dottenbr** [elexess/erp-shipment#130]
Pressing the button doesn’t do anything 

shipment-01597-1 on Production 

![image](https://user-images.githubusercontent.com/9136094/140387302-784f30dc-d950-40ef-b555-052b45aef83c.jpg)

**Comment by dottenbr** [comment]
@creamdory please triage

**Comment by dottenbr** [comment]
This happens when popups are blocked by the browser :-( can we detect that?

**Comment by creamdory** [comment]
@dottenbr I believe we can. We can detect then throw a handled error. Created issue https://github.com/elexess/erp-shipment/issues/132 for triage but will be catered to next sprint since not a bug.
