### ISSUE TITLE
[1pt]Wrong address by default 

### ISSUE THREAD

**Issue by dottenbr** [elexess/erp-shipment#131]
When I create a shipment it uses eso Romania as an address by default even though the company is eso Germany. This is wrong. 

![E6D16025-5E37-4A1E-AF55-ED9EAD68F4C8](https://user-images.githubusercontent.com/9136094/140391395-35a2b599-010a-4580-a36c-744e0e89bd4e.jpeg)

**Comment by dottenbr** [comment]
@creamdory urgent please triage

**Comment by creamdory** [comment]
@kkulloters so far no default set in field on Doctype setup level and does not pull from default Company of user. Please check script level. Thanks!

**Comment by kkulloters** [comment]
hello @creamdory 
I checked the script and seems it does fetch the correct address 

set's the company 
![image](https://user-images.githubusercontent.com/40702858/140444959-37837e83-5024-4374-8753-d6174625b27c.png)

sets the pickup address name
![image](https://user-images.githubusercontent.com/40702858/140447184-a0eafaf1-5674-407d-b41f-6f96b82f0c0b.png)

**Comment by kkulloters** [comment]
hello @creamdory @dottenbr 

It seems like the fetching is correct and data was not set correctly as I check the DN it has an SC address set 
![image](https://user-images.githubusercontent.com/40702858/140454265-02538369-d800-4a6f-a3c1-5eeab3f0cdd4.png)

and I also check the code when creating shipment from the DN it fetches the company address that was set in DN 
![image](https://user-images.githubusercontent.com/40702858/140454416-197cc3f2-50ed-402b-932c-1ba00635c397.png)

**Comment by dottenbr** [comment]
@kkulloters and @creamdory why do our German delivery notes have ESO Romania as addresses? This makes no sense.

**Comment by kkulloters** [comment]
hello @dottenbr I will look unto the code of fetching address in DN

**Comment by creamdory** [comment]
@dottenbr It was setup in our Company.

<img width="891" alt="ESO Electronic Service Ottenbreit GmbH 2021-11-05 16-06-21" src="https://user-images.githubusercontent.com/21003054/140478453-1c88b89b-05b1-4c72-a821-1f7586aba2b1.png">

Created by KC.
https://erp.eso-electronic.com/desk#Form/Address/SC%20ESO%20Electronic%20S.R.L-Billing

I am tracing if there is a Github issue for this but so far I cannot find any.

I am also seeing this which I believe is incorrect.

<img width="891" alt="ESO Electronic Service Ottenbreit GmbH 2021-11-05 16-06-21" src="https://user-images.githubusercontent.com/21003054/140479254-442fcc96-2691-4eb9-b4f7-28b1a1b80c41.png">

I believe it is from this feature in Address.

<img width="1246" alt="is your company" src="https://user-images.githubusercontent.com/21003054/140479371-bd0d2c55-d1fe-4de7-ab38-ce81a1ec4c0b.png">

**Comment by creamdory** [comment]
Let us know if this is not intended so we can investigate further and see if it needs patching or cleanup.

**Comment by jeremythegreat01** [comment]
Update: As of this writing, there are 3 "company addresses" checked. I will be removing REICH for now because it is not part of ESO.

![image](https://user-images.githubusercontent.com/35899441/142803064-297b5a48-e3d3-4864-9c3d-7a6a16985074.png)

Removed check mark for "Is your company address" and only linked to their own Customer DocType entry:
![image](https://user-images.githubusercontent.com/35899441/142803122-2303db61-8471-468e-a675-f4a0cb059525.png)

**Comment by creamdory** [comment]
@jeremythegreat01 I believe I know what happen here. So basically, RO does this "dropshipping" thing where they needed to "order" from ESO but delivers to the client directly like Reich. So they had to add the Reich address to ESO to use it as shipping address. Billing Address is still ESO.

**Comment by creamdory** [comment]
@jeremythegreat01 ERPNext had a dropshipping functionality. We can ask @ArundhatiSh and @francitj to look at it so we can have it implemented properly for this usecase.

**Comment by kkulloters** [comment]
Hello @jeremythegreat01 @creamdory I haven't continued working on this cos I need some confirmation 

Is there still a technical stuff that I need to do with this?

**Comment by creamdory** [comment]
@jeremythegreat01 @kkulloters we can close this issue since this is data related. @jeremythegreat01 I will create an issue for the dropshipping implementation.
